# Use an official Python runtime as a parent image
FROM python:3
FROM williamyeh/java8

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app

# Install any needed packages specified in requirements.txt
RUN apt-get update && \
	apt-get install -y postgresql \
#	oracle-java8-installer \
#	java-common \
	libpq-dev \
	libpq5 \
	libc-dev \
	enchant \
	python3-numpy \
	python3-enchant \
	build-essential \
	python3-pip && \
	apt-get clean

RUN	apt-get install -y gcc gfortran python-dev libblas-dev liblapack-dev cython && \
	pip3 install --upgrade pip && \
	pip3 install numpy

RUN	pip3 install scipy

RUN	pip3 install gensim

RUN	pip3 install psycopg2==2.6.2 && \
 	pip3 install nltk==3.2.4 && \
	pip3 install Django>=1.9.7 && \
	pip3 install beautifulsoup4==4.6.0 && \
	pip3 install Pillow>=3.3.0 && \
	pip3 install lxml>=3.6.0 && \
	pip3 install pyenchant && \
	pip3 install jieba3k>=0.35.1 feedparser==5.2.1 virtualenv==15.1.0 && \
	python3 -m nltk.downloader punkt  && \
	python3 -m nltk.downloader averaged_perceptron_tagger

COPY requirements.txt /tmp/

RUN	pip3 install --requirement /tmp/requirements.txt

COPY . /tmp/

ADD . /app

CMD gunicorn -b :$PORT mysite.wsgi

# Make port 80 available to the world outside this container
EXPOSE 80
EXPOSE 8000

# Define environment variable
ENV NAME World

# Run app.py when the container launches
CMD ["./start.sh"]
