# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-24 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20170623_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='authors',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
