# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 21:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_article_authors'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-pub_date']},
        ),
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': ['-pub_date']},
        ),
    ]
