# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-11 21:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20170704_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='story_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='api.Story'),
        ),
    ]
