# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 21:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20170718_2031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence_id', models.IntegerField()),
                ('text', models.CharField(max_length=5000, null=True)),
                ('upvoted', models.IntegerField(default=0)),
                ('downvoted', models.IntegerField(default=0)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fact_article', to='api.Article')),
            ],
        ),
    ]
