# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 19:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0011_auto_20170728_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='downvoted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='downvoted_by',
            field=models.ManyToManyField(related_name='com_downv_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='upvoted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='upvoted_by',
            field=models.ManyToManyField(related_name='com_upv_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
