# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 23:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0014_auto_20170728_1910'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('url', models.URLField(blank=True, null=True)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('upvoted', models.IntegerField(default=0)),
                ('downvoted', models.IntegerField(default=0)),
                ('downvoted_by', models.ManyToManyField(related_name='cit_downv_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterModelOptions(
            name='fact',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='comment',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comm_recipient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='citation',
            name='fact_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cit_fact', to='api.Fact'),
        ),
        migrations.AddField(
            model_name='citation',
            name='upvoted_by',
            field=models.ManyToManyField(related_name='cit_upv_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='citation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cit_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
