# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 20:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0016_citation_approval'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitationComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('text', models.TextField()),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('upvoted', models.IntegerField(default=0)),
                ('downvoted', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='hotness',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='citationcomment',
            name='article_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cit_comm_article', to='api.Article'),
        ),
        migrations.AddField(
            model_name='citationcomment',
            name='citation_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comm_citation', to='api.Citation'),
        ),
        migrations.AddField(
            model_name='citationcomment',
            name='downvoted_by',
            field=models.ManyToManyField(related_name='cit_com_downv_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='citationcomment',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cit_comm_recipient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='citationcomment',
            name='upvoted_by',
            field=models.ManyToManyField(related_name='cit_com_upv_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='citationcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cit_comm_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
