# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 21:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20170810_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citationcomment',
            name='article_id',
        ),
    ]
