# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_citationcomment_article_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': ['hotness', '-pub_date']},
        ),
        migrations.AlterField(
            model_name='story',
            name='hotness',
            field=models.IntegerField(default=0),
        ),
    ]
