# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-18 19:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20170817_2126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': ['hotness', '-pub_date']},
        ),
    ]
