# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-20 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20170818_1957'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': ['-date', '-hotness']},
        ),
        migrations.AddField(
            model_name='story',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
