# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-21 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20170820_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='country',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='party',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='party',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='party',
            name='url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='source',
            name='affiliations',
            field=models.ManyToManyField(blank=True, related_name='affiliation', to='api.Party'),
        ),
        migrations.AlterField(
            model_name='source',
            name='url',
            field=models.URLField(max_length=500),
        ),
    ]
