# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-24 08:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0025_source_bias'),
    ]

    operations = [
        migrations.AddField(
            model_name='fact',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fact_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
