# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-06 21:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170918_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='citation',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='citation',
            name='reported_by',
            field=models.ManyToManyField(related_name='cit_report_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='reported_by',
            field=models.ManyToManyField(related_name='com_report_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
